services:
  fastapi:
    build: .
    container_name: fastapi-app

    env_file:
      - .env

    environment:
      - key=${key}

    restart: unless-stopped

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - __pycache__/
            - .uv/

  nginx:
    image: nginx:alpine
    container_name: nginx

    environment:
      - DOMAIN=${DOMAIN}

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./cert:/etc/letsencrypt:ro

    depends_on:
      - fastapi

    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot

    volumes:
      - ./cert:/etc/letsencrypt
      - ./cert:/var/lib/letsencrypt